[workspace]
members = [
    "./crates/file",
    "./crates/file_local",
    "./crates/utils",
    "./crates/vindex",
    "./crates/sync",
    "./crates/chunk",
    "./crates/trie",
    "./crates/db"
]

[profile.bench]
debug = true
