[package]
name = "utils_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
once_cell = "1.9"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
syn = "1.0"