[package]
name = "vindex"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
serde = { version = "1.0", features = ["derive"] }
crdts = "7.3.0"
uuid = "1.3.4"
thiserror = "1.0"
libp2p = { version = "0.51.2", features = ["serde"] }