[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = { version = "0.21", features = ["lz4"], default-features = false }
thiserror = "1.0"
parking_lot = "0.12.1"

[dev-dependencies]
test-results = "0.1.2"